Address = "0x04d6...73F197ccd186"
RPC = "https://example-rpc.validator.io"
Website = "https://example-validator.io"
Description = "This is a example validator on BSC network"
Contact = "example-validator@mail.com"