Address = "0xBA4233f6e478DB76698b0A5000972Af0196b7bE1"
PRC = "htttps://blockrazor-builder-frankfurt.48.club"
Website = "https://www.blockrazor.io"
Description = "we build this neutral  builder with multiple strategies and algorithms to make most valuable block，More detail can be seen in our official website and hope you enjoy your journey in BlockRazor"
Contact = "support@blockrazor.io"
