Address = "0x6Dddf681C908705472D09B1D7036B2241B50e5c7"
RPC = "https://bsc-builder-report-ap.blocksmith.org/"
Website = "https://blocksmith.org"
Description = "We Empower Teams to Excel in DeFi Trading"
Contact = "dj@blocksmith.org"