Address = "0x79102dB16781ddDfF63F301C9Be557Fd1Dd48fA0"
RPC = "https://bsc-mainnet.nodereal.io/v1/<API_KEY>"
Website = "https://nodereal.io/"
Description = "Advanced Infrastructure Provider for EVM blockchains."